### ISSUE TITLE
[BUG] no-commit-to-branch fails in GH Action on master

### ISSUE THREAD

**Issue by sblack4** [rhythmictech/terraform-terraform-template#12]
**Describe the bug**
The `no-commit-to-branch` fails in GH Action on the master branch

**Expected behavior**
The `no-commit-to-branch` shouldn't fail on the master branch in GH actions

**Additional context**
see https://github.com/rhythmictech/terraform-anycloud-template/runs/739820257

**Comment by sblack4** [comment]
@smiller171 do you think we could just skip the `no-commit-to-branch` hook in the pre-commit-check pipeline to fix?

**Comment by smiller171** [comment]
Yeah, it probably makes sense not to run this in GH Actions. Even if it triggered at the right time, by that point the commit is already done.

**Comment by sblack4** [comment]
fixed by #13
