### ISSUE TITLE
[Feature] please remove linter bot

### ISSUE THREAD

**Issue by sblack4** [rhythmictech/terraform-terraform-template#29]
I'm tired of seeing this. My preferred experience would be to get a failed workflow and the option to fix it myself or ignore it and continue anyways.  

![image](https://user-images.githubusercontent.com/15880760/109049969-e2674700-76a6-11eb-8b02-e666a29495bf.png)

it's from https://github.com/rhythmictech/terraform-azurerm-postgresql/pull/5/commits/6b0fb534f3d46700861cc77759962a5bdb6382f1

**Comment by smiller171** [comment]
Yeah, when I added that our maturity level with this stuff was a lot lower, and it's proven to be more annoying than useful. Sorry for inflicting this on us.
